version: '3'

services:
  etcd1:
    build:
      context: .
      dockerfile: etcd/Dockerfile
    command: /etcd/bin/run-etcd.sh /etcd/bin/etcd etcd1
    ports:
      - "2379:2379"
    cap_add:
      - NET_ADMIN

  etcd2:
    build:
      context: .
      dockerfile: etcd/Dockerfile
    command: /etcd/bin/run-etcd.sh /etcd/bin/etcd etcd2
    ports:
      - "3379:2379"
    cap_add:
      - NET_ADMIN

  etcd3:
    build:
      context: .
      dockerfile: etcd/Dockerfile
    command: /etcd/bin/run-etcd.sh /etcd/bin/etcd etcd3
    ports:
      - "4379:2379"
    cap_add:
      - NET_ADMIN
