version: '3'

services:
  etcd1:
    build:
      context: .
      dockerfile: etcd/Dockerfile
    command: /etcd/bin/runner /etcd/bin/etcd etcd1 /etc/runner.yml
    volumes:
      - "./config/runner.yml:/etc/runner.yml"
    ports:
      - "2379:2379"
    cap_add:
      - NET_ADMIN
    networks:
      - etcd12
      - etcd31
      - prom1

  etcd2:
    build:
      context: .
      dockerfile: etcd/Dockerfile
    command: /etcd/bin/runner /etcd/bin/etcd etcd2 /etc/runner.yml
    volumes:
      - "./config/runner.yml:/etc/runner.yml"
    ports:
      - "3379:2379"
    cap_add:
      - NET_ADMIN
    networks:
      - etcd12
      - etcd23
      - prom2

  etcd3:
    build:
      context: .
      dockerfile: etcd/Dockerfile
    command: /etcd/bin/runner /etcd/bin/etcd etcd3 /etc/runner.yml
    volumes:
      - "./config/runner.yml:/etc/runner.yml"
    ports:
      - "4379:2379"
    cap_add:
      - NET_ADMIN
    networks:
      - etcd23
      - etcd31
      - prom3

  prometheus:
    image: prom/prometheus
    volumes:
      - "./config/prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    networks:
      - prom1
      - prom2
      - prom3

networks:
  etcd12:
    driver: bridge
  etcd23:
    driver: bridge
  etcd31:
    driver: bridge
  prom1:
    driver: bridge
  prom2:
    driver: bridge
  prom3:
    driver: bridge
