global:
  scrape_interval: 10s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - prometheus:9090
  - job_name: etcd
    static_configs:
      - targets:
        - etcd1:2379
        - etcd2:2379
        - etcd3:2379
