peer_config:
  etcd1:
    outbound_latency_ms:
      etcd120: 30
      etcd310: 30
  etcd2:
    outbound_latency_ms:
      etcd120: 30
      etcd230: 10
  etcd3:
    outbound_latency_ms:
      etcd230: 10
      etcd310: 30
